-- +goose Up

-- Surrogate keys use uuidv7(), the project-wide convention (D56): native
-- to Postgres 18 (no extension), chosen over a serial/bigserial key so no
-- row's id discloses how many matches/users/sessions exist, and over
-- gen_random_uuid()'s v4 because v7's leading timestamp keeps new rows
-- index-local instead of scattering inserts across the whole btree.
-- Stated once here; every id column below follows it.

CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  email TEXT UNIQUE NULL,
  display_name TEXT NOT NULL,
  is_guest BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- D19/D53's users.email_suppressed_at and match_players' D16-D19 columns
-- land in the next migration (#313) — this table carries only what RFC-001
-- §7.2 specifies outside those decisions.

CREATE TABLE auth_codes (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  email TEXT NOT NULL,
  code_hash BYTEA NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ NULL,
  attempts INT NOT NULL DEFAULT 0
);

CREATE TABLE sessions (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  -- RESTRICT, not a cascading delete: a user is never deleted while a live
  -- session references them (v1 has no account-deletion flow to weigh
  -- against this; that tradeoff is a later decision, not an implicit one).
  user_id UUID NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE matches (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  -- abandoned is listed even though nothing produces it yet — D22 (open)
  -- is what would make it reachable. Omitting it now just means a later
  -- migration reopens this CHECK for a value the schema already knew about.
  status TEXT NOT NULL DEFAULT 'lobby'
    CHECK (status IN ('lobby', 'active', 'finished', 'abandoned')),
  config JSONB NOT NULL,       -- the frozen game.Config (RFC-001 §6.2)
  seed BYTEA NOT NULL,
  round INT NOT NULL DEFAULT 0,
  timer_seconds INT NULL,      -- sync tables
  deadline_seconds INT NULL,   -- async tables
  deadline_at TIMESTAMPTZ NULL,
  -- RESTRICT: same reasoning as sessions.user_id above — the host is never
  -- deleted out from under a match that still names them.
  created_by UUID NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at TIMESTAMPTZ NULL
);

CREATE TABLE match_players (
  match_id UUID NOT NULL REFERENCES matches (id) ON DELETE RESTRICT,
  seat SMALLINT NOT NULL,
  -- RESTRICT, same reasoning as sessions.user_id/matches.created_by above.
  -- NULL itself (a bot seat) is unaffected by ON DELETE, which only
  -- governs what happens to *existing* non-null references.
  user_id UUID NULL REFERENCES users (id) ON DELETE RESTRICT,
  bot_kind TEXT NULL,
  faction TEXT NOT NULL,
  joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- derived/rebuildable read cache for the lobby list (RFC-001 §8.2) —
  -- not authority, same status as events/match_summary below.
  missed_deadlines INT NOT NULL DEFAULT 0,
  PRIMARY KEY (match_id, seat)
);
-- D16's last_seen_round, D17's invite_link_id, D19's email_pref and
-- unsubscribe_token_hash all land on this table in #313, not here.

-- THE LOG. orders' primary key is not an optimisation — it is GDD §18's
-- rule ("Resubmission is allowed while the round is open; the last
-- submission stands") enforced structurally: a resubmission during an open
-- round is `ON CONFLICT (match_id, round, seat) DO UPDATE`, which this key
-- is what makes possible.
CREATE TABLE orders (
  match_id UUID NOT NULL REFERENCES matches (id) ON DELETE RESTRICT,
  round INT NOT NULL,
  seat SMALLINT NOT NULL,
  payload JSONB NOT NULL,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- RFC-001 §8.2: Autopilot is derived as `source <> 'human'` over the
  -- last two rounds, never a stored flag. An unconstrained free-text
  -- column here means a typo in an insert silently changes whether a
  -- player reads as being on Autopilot.
  source TEXT NOT NULL CHECK (source IN ('human', 'bot', 'default')),
  -- match_id alone only proves the match exists, not that seat is an
  -- actual participant in it — without this, an insert for seat = 999
  -- on a real match would succeed and store an order that maps to no
  -- participant, which fold/replay has no way to make sense of later.
  FOREIGN KEY (match_id, seat)
    REFERENCES match_players (match_id, seat)
    ON DELETE RESTRICT,
  PRIMARY KEY (match_id, round, seat)
);

-- Derived, rebuildable projections of the order log — never authority.
-- Regenerated by `cmd/replay --rebuild` (RFC-001 §7.1/§7.2). ON DELETE
-- RESTRICT on every FK below (into orders, events, match_summary, outbox)
-- is deliberate, not the implicit Postgres default: RFC-001 §18 says
-- losing the order log means matches cannot be reconstructed, because
-- there is no state table to fall back on, and that guarantee belongs in
-- the schema, not only in application code that might delete a match row
-- for an unrelated reason.
CREATE TABLE events (
  match_id UUID NOT NULL REFERENCES matches (id) ON DELETE RESTRICT,
  round INT NOT NULL,
  seq INT NOT NULL,
  kind TEXT NOT NULL,
  payload JSONB NOT NULL,
  PRIMARY KEY (match_id, round, seq)
);
COMMENT ON TABLE events IS
  'Derived, rebuildable projection of the order log -- never authority. '
  'Regenerated by cmd/replay --rebuild (RFC-001 Sec.7.1/7.2).';

CREATE TABLE match_summary (
  match_id UUID NOT NULL REFERENCES matches (id) ON DELETE RESTRICT,
  round INT NOT NULL,
  submitted_seats SMALLINT[] NOT NULL DEFAULT '{}',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (match_id, round)
);
COMMENT ON TABLE match_summary IS
  'Derived, rebuildable projection of the order log -- never authority. '
  'Regenerated by cmd/replay --rebuild (RFC-001 Sec.7.1/7.2).';

CREATE TABLE outbox (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  to_email TEXT NOT NULL,
  template TEXT NOT NULL,
  payload JSONB NOT NULL,
  attempts INT NOT NULL DEFAULT 0,
  match_id UUID NULL REFERENCES matches (id) ON DELETE RESTRICT,
  round INT NULL,
  seat SMALLINT NULL,
  send_after TIMESTAMPTZ NOT NULL DEFAULT now(),
  sent_at TIMESTAMPTZ NULL,
  last_error TEXT NULL
);

-- Partial, not a plain UNIQUE constraint: Postgres treats NULLs as
-- distinct, so `UNIQUE (match_id, round, seat, template)` does nothing for
-- otp -- it has no match_id, so every login row would compare unique.
-- otp is rate-limited per email (RFC-001 Sec.12.2), not deduplicated
-- here: a second login request is a legitimate second code.
-- See RFC-001 Sec.13.1.
CREATE UNIQUE INDEX outbox_match_dedup
  ON outbox (match_id, round, seat, template)
  WHERE match_id IS NOT NULL;

-- +goose Down

-- Reversible: nothing else in the repository writes to these tables yet,
-- so dropping them loses no live data at this stage of the project.
DROP TABLE outbox;
DROP TABLE match_summary;
DROP TABLE events;
DROP TABLE orders;
DROP TABLE match_players;
DROP TABLE matches;
DROP TABLE sessions;
DROP TABLE auth_codes;
DROP TABLE users;
