// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package store

import (
	"context"

	"github.com/garnizeh/cinzal/internal/game"
)

const deleteEventsByMatch = `-- name: DeleteEventsByMatch :exec
DELETE FROM events
WHERE match_id = $1
`

func (q *Queries) DeleteEventsByMatch(ctx context.Context, matchID game.MatchID) error {
	_, err := q.db.Exec(ctx, deleteEventsByMatch, matchID)
	return err
}
