// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: match_players.sql

package store

import (
	"context"

	"github.com/garnizeh/cinzal/internal/game"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMatchPlayer = `-- name: CreateMatchPlayer :one

INSERT INTO match_players (
  match_id, seat, user_id, bot_kind, faction, unsubscribe_token_hash
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING match_id, seat, user_id, bot_kind, faction, joined_at, missed_deadlines, last_seen_round, invite_link_id, email_pref, unsubscribe_token_hash
`

type CreateMatchPlayerParams struct {
	MatchID              game.MatchID
	Seat                 game.SeatID
	UserID               *pgtype.UUID
	BotKind              *string
	Faction              string
	UnsubscribeTokenHash []byte
}

// match_players.sql — M3 (issue #315).
//
// Callers: CreateMatchPlayer is internal/match's seat-creation path (M3/M5:
// lobby formation and, later, POST /m/{id}/join) — one call per seat, never
// batched, so a caller cannot accidentally seat a player it didn't mean to.
// ListMatchPlayers is internal/match's own roster/lobby read (M3, #318/#319)
// and, later, the lobby list (RFC-001 §8.2).
//
// ListMatchPlayers returns every seat's roster row for ONE match_id the
// caller already scoped the call to — seat number, faction, bot_kind. This
// is lobby/roster data, not the game view: it carries no order payload, no
// fog-scoped field, nothing GDD §7.1 would gate behind sight or trail. It is
// still scoped to one match_id per call — nothing here lists across matches.
//
// last_seen_round, invite_link_id, email_pref (migration 00002, D16-D19) all
// have schema defaults and are read/written by their own M5 tasks, not this
// one — omitted from CreateMatchPlayer's column list and from
// ListMatchPlayers' projection on purpose. unsubscribe_token_hash is the one
// exception: it is BYTEA NOT NULL with no default (D19 mints it "once at
// seat creation, unconditionally, for every seat"), so CreateMatchPlayer
// must take it as a parameter or the INSERT fails the NOT NULL constraint —
// the hash itself is computed by the M5 caller (sha256 of 32 crypto/rand
// bytes, per D19), never by this query.
func (q *Queries) CreateMatchPlayer(ctx context.Context, arg CreateMatchPlayerParams) (MatchPlayer, error) {
	row := q.db.QueryRow(ctx, createMatchPlayer,
		arg.MatchID,
		arg.Seat,
		arg.UserID,
		arg.BotKind,
		arg.Faction,
		arg.UnsubscribeTokenHash,
	)
	var i MatchPlayer
	err := row.Scan(
		&i.MatchID,
		&i.Seat,
		&i.UserID,
		&i.BotKind,
		&i.Faction,
		&i.JoinedAt,
		&i.MissedDeadlines,
		&i.LastSeenRound,
		&i.InviteLinkID,
		&i.EmailPref,
		&i.UnsubscribeTokenHash,
	)
	return i, err
}

const listMatchPlayers = `-- name: ListMatchPlayers :many
SELECT match_id, seat, user_id, bot_kind, faction, joined_at, missed_deadlines
FROM match_players
WHERE match_id = $1
ORDER BY seat
`

type ListMatchPlayersRow struct {
	MatchID         game.MatchID
	Seat            game.SeatID
	UserID          *pgtype.UUID
	BotKind         *string
	Faction         string
	JoinedAt        pgtype.Timestamptz
	MissedDeadlines int32
}

func (q *Queries) ListMatchPlayers(ctx context.Context, matchID game.MatchID) ([]ListMatchPlayersRow, error) {
	rows, err := q.db.Query(ctx, listMatchPlayers, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchPlayersRow
	for rows.Next() {
		var i ListMatchPlayersRow
		if err := rows.Scan(
			&i.MatchID,
			&i.Seat,
			&i.UserID,
			&i.BotKind,
			&i.Faction,
			&i.JoinedAt,
			&i.MissedDeadlines,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
