// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package store

import (
	"context"

	"github.com/garnizeh/cinzal/internal/game"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMatch = `-- name: CreateMatch :one

INSERT INTO matches (
  config, seed, created_by, timer_seconds, deadline_seconds
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, status, config, seed, round, timer_seconds, deadline_seconds, deadline_at, created_by, created_at, finished_at
`

type CreateMatchParams struct {
	Config          []byte
	Seed            []byte
	CreatedBy       pgtype.UUID
	TimerSeconds    *int32
	DeadlineSeconds *int32
}

// matches.sql — M3 (issue #315).
//
// Callers: CreateMatch is internal/match's match-creation path (M3, #318) —
// called once, at the moment a lobby becomes a match, freezing config and
// seed for the match's whole lifetime (RFC-001 §6.2: "a match created under
// v1 rules finishes under v1 rules"). GetMatch is internal/match's own
// load/fold-start path (M3, #319) and cmd/replay (M4) — both read exactly
// one match's own row by its own id, which the caller already possesses
// (from a URL path segment, a job argument, or its own prior CreateMatch
// call); neither query can be handed an id it wasn't already scoped to.
//
// config and seed surface as []byte here — D44's codec boundary, not
// decoded until a layer above internal/store.
//
// Locking variants (SELECT ... FOR UPDATE, round-advance UPDATE) belong to
// the round tick, M4's own task — out of scope here.
func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch,
		arg.Config,
		arg.Seed,
		arg.CreatedBy,
		arg.TimerSeconds,
		arg.DeadlineSeconds,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Config,
		&i.Seed,
		&i.Round,
		&i.TimerSeconds,
		&i.DeadlineSeconds,
		&i.DeadlineAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getMatch = `-- name: GetMatch :one
SELECT id, status, config, seed, round, timer_seconds, deadline_seconds, deadline_at, created_by, created_at, finished_at FROM matches
WHERE id = $1
`

func (q *Queries) GetMatch(ctx context.Context, id game.MatchID) (Match, error) {
	row := q.db.QueryRow(ctx, getMatch, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Config,
		&i.Seed,
		&i.Round,
		&i.TimerSeconds,
		&i.DeadlineSeconds,
		&i.DeadlineAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}
