// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/garnizeh/cinzal/internal/game"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthCode struct {
	ID         pgtype.UUID
	Email      string
	CodeHash   []byte
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	Attempts   int32
}

// Authoritative state with no order-log equivalent -- never a derived projection, out of cmd/replay --rebuild's scope, and never rendered to any seat but its own author. See D18.
type BoardNote struct {
	MatchID   pgtype.UUID
	Seat      int16
	Slot      int16
	NodeID    *int32
	Round     int32
	Body      string
	UpdatedAt pgtype.Timestamptz
}

// Derived, rebuildable projection of the order log -- never authority. Regenerated by cmd/replay --rebuild (RFC-001 Sec.7.1/7.2).
type Event struct {
	MatchID game.MatchID
	Round   game.RoundNumber
	Seq     int32
	Kind    string
	Payload []byte
}

// Authoritative state with no order-log equivalent -- never a derived projection, out of cmd/replay --rebuild's scope. See D17.
type InviteLink struct {
	ID        pgtype.UUID
	MatchID   pgtype.UUID
	TokenHash []byte
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type Match struct {
	ID              game.MatchID
	Status          string
	Config          []byte
	Seed            []byte
	Round           game.RoundNumber
	TimerSeconds    *int32
	DeadlineSeconds *int32
	DeadlineAt      pgtype.Timestamptz
	CreatedBy       pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
}

type MatchPlayer struct {
	MatchID         game.MatchID
	Seat            game.SeatID
	UserID          pgtype.UUID
	BotKind         *string
	Faction         string
	JoinedAt        pgtype.Timestamptz
	MissedDeadlines int32
	// Derived, rebuildable read cache of the order log -- same category as missed_deadlines, events and match_summary, not an exception to Sec.7.1. See D16, corrected by D52.
	LastSeenRound int32
	InviteLinkID  pgtype.UUID
	// D19: per-match email volume preference. daily_digest deferred -- not one of these three.
	EmailPref string
	// D19: one-click-unsubscribe bearer token, sha256 digest, minted at seat creation regardless of address eligibility (D53). Directly-written state, not derived -- nothing in orders determines a preference or a token.
	UnsubscribeTokenHash []byte
}

// Derived, rebuildable projection of the order log -- never authority. Regenerated by cmd/replay --rebuild (RFC-001 Sec.7.1/7.2).
type MatchSummary struct {
	MatchID        game.MatchID
	Round          game.RoundNumber
	SubmittedSeats []game.SeatID
	UpdatedAt      pgtype.Timestamptz
}

type Order struct {
	MatchID     game.MatchID
	Round       game.RoundNumber
	Seat        game.SeatID
	Payload     []byte
	SubmittedAt pgtype.Timestamptz
	Source      string
}

type Outbox struct {
	ID        pgtype.UUID
	ToEmail   string
	Template  string
	Payload   []byte
	Attempts  int32
	MatchID   pgtype.UUID
	Round     *int32
	Seat      *int16
	SendAfter pgtype.Timestamptz
	SentAt    pgtype.Timestamptz
	LastError *string
}

// Generic token-bucket rate limiter (D20). Authoritative state with no order-log equivalent -- never a derived projection, out of cmd/replay --rebuild's scope, the same category as invite_links/board_notes.
type RateLimit struct {
	Scope     string
	Key       string
	Tokens    float64
	UpdatedAt pgtype.Timestamptz
}

type Session struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
}

type User struct {
	ID                pgtype.UUID
	Email             *string
	DisplayName       string
	IsGuest           bool
	CreatedAt         pgtype.Timestamptz
	EmailSuppressedAt pgtype.Timestamptz
}
